services:

  postgres:
    image: postgres:16-alpine
    ports:
    - "5432:5432"
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB:       ${POSTGRES_DB}
      POSTGRES_USER:     ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d project_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  qdrant:
    image: qdrant/qdrant:v1.17.0
    container_name: qdrant
    ports:
      - "${QDRANT_PORT}:${QDRANT_PORT}"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - backend
    environment:
      - QDRANT__TELEMETRY_DISABLED=true
      - QDRANT__SERVICE__MAX_WORKERS=2
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'cat /dev/null > /dev/tcp/localhost/${QDRANT_PORT}'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  model-service:
    build:
      context: .
      dockerfile: services/model_service/Dockerfile
    image: semantic-search-model-service:latest
    container_name: model-service
    networks:
      - backend
    environment:
      - HF_HOME=/app/.cache/huggingface
      - TRANSFORMERS_OFFLINE=1 #0
      - HF_DATASETS_OFFLINE=1  #0
    volumes:
      - hf_cache:/app/.cache/huggingface
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s

  user-service:
    build:
      context: .
      dockerfile: services/user_service/Dockerfile
    image: semantic-search-user-service:latest
    container_name: user-service
    networks:
      - backend
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8001/health')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  document-service:
    build:
      context: .
      dockerfile: services/document_service/Dockerfile
    image: semantic-search-document-service:latest
    container_name: document-service
    networks:
      - backend
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_healthy
      model-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8002/health')"]
      interval: 10s
      timeout: 5s
      retries: 5

  search-service:
    build:
      context: .
      dockerfile: services/search_service/Dockerfile
    image: semantic-search-search-service:latest
    container_name: search-service
    ports:
      - "8003:8003"
    networks:
      - backend
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_healthy
      model-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8003/health')"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway:
    build:
      context: .
      dockerfile: services/gateway_service/Dockerfile
    image: semantic-search-gateway:latest
    container_name: gateway
    ports:
      - "${GATEWAY_PORT}:8080"
    networks:
      - backend
    env_file:
      - .env
    depends_on:
      user-service:
        condition: service_healthy
      document-service:
        condition: service_healthy
      search-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  qdrant_data:
  hf_cache: