pipeline {
    agent any

    stages {
        
        stage('Checkout') {
            steps {
                checkout scm
            }
        }        

        stage('Test user_service') {
            steps {
                sh '''
                    cd services/user_service
                    docker-compose -f docker-compose.test.yaml up --build --abort-on-container-exit
                '''
            }
        }
    }

    post {
        always {
            // Cleanup
            sh '''
                cd "services/user_service"
                docker-compose -f docker-compose.test.yml down -v || true
            '''
            cleanWs()
        }
    }
}