apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qdrant
spec:
  serviceName: "qdrant"
  replicas: {{ .Values.qdrant.replicas }}
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
        - name: qdrant
          image: "{{ .Values.qdrant.image.repository }}:{{ .Values.qdrant.image.tag }}"
          ports:
            - containerPort: {{ .Values.qdrant.port }}
          env:
            - name: QDRANT__TELEMETRY_DISABLED
              value: {{ .Values.qdrant.env.telemetryDisabled | quote }}
            - name: QDRANT__SERVICE__MAX_WORKERS
              value: {{ .Values.qdrant.env.maxWorkers | quote }}
          volumeMounts:
            - name: qdrant-storage
              mountPath: /qdrant/storage
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.qdrant.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.qdrant.port }}
            initialDelaySeconds: 30
            periodSeconds: 15
      volumes:
        - name: qdrant-storage
          persistentVolumeClaim:
            claimName: qdrant-pvc