apiVersion: v1
kind: Service
metadata:
  name: document-service
spec:
  selector:
    app: document-service
  ports:
    - port: {{ .Values.documentService.port }}
      targetPort: {{ .Values.documentService.port }}
  type: ClusterIP 