pipeline {
    agent any

    stages {
        
        stage('Checkout') {
            steps {
                checkout scm
            }
        }        

        stage('Test gateway_service') {
            steps {
                sh '''
                    cd services/gateway_service
                    docker-compose -f docker-compose.test.yaml up --build --abort-on-container-exit
                '''
            }
        }
    }

    post {
        always {
            // Cleanup
            sh '''
                cd "services/gateway_service"
                docker-compose -f docker-compose.test.yaml down -v || true
            '''
            cleanWs()
        }
    }
}