pipeline {
    agent any

    stages {

        stage('Test search_service') {
            steps {
                sh '''
                    cd services/search_service
                    docker-compose -f docker-compose.test.yaml up --build --abort-on-container-exit
                '''
            }
        }
    }

    post {
        always {
            // Cleanup: stop and remove Postgres container
            sh '''
                cd services/search_service
                docker-compose -f docker-compose.test.yml down -v || true
            '''
            cleanWs()
        }
    }
}