pipeline {
    agent any

    stages {
        
        stage('Checkout') {
            steps {
                checkout scm
            }
        }        

        stage('Test search_service') {
            environment {
                HOME = '/tmp'
            }
            steps {
                sh '''
                    mkdir -p /tmp/.docker
                    echo '{}' > /tmp/.docker/config.json
                    echo "HOME=$HOME"
                    docker info
                    cd services/search_service
                    docker-compose -f docker-compose.test.yaml --env-file .env.test up --build --abort-on-container-exit
                '''
            }
        }
    }

    post {
        always {
            // Cleanup
            sh '''
                cd "services/search_service"
                docker-compose -f docker-compose.test.yml down -v || true
            '''
            cleanWs()
        }
    }
}