name: CI - model_service

on:
  push:
    branches: [develop]
    paths:
      - 'services/model_service/**'
      - 'services/common/**'
      - '.github/workflows/ci_model_service.yml'

  pull_request:
    branches: [develop]
    paths:
      - 'services/model_service/**'
      - 'services/common/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          cd services/model_service
          docker compose -f docker-compose.test.yaml up --build --abort-on-container-exit

      - name: Cleanup
        if: always()
        run: |
          cd services/model_service
          docker compose -f docker-compose.test.yaml down -v